<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Aug 29, 2020
*/

class CreateWorkerTable extends Migration {

    public function up() {
        Schema::create('worker', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 200)->nullable();
            $table->string('hospital', 200)->nullable()->default('Non');
            $table->string('phone', 100)->nullable();
            $table->string('email', 200)->nullable();
            $table->string('languages', 100)->nullable();
            $table->string('city', 100)->nullable();
            $table->string('country', 3)->nullable();
            $table->string('gender', 100)->nullable();
            $table->string('job', 100)->nullable();
            $table->string('specialty', 100)->nullable();
        });
    }

    public function down() {
        Schema::dropIfExists('worker');
    }
}
