<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Aug 31, 2020
*/

class CreateProductsFaqTable extends Migration {

    public function up() {
        Schema::create('products_faq', function (Blueprint $table) {
            $table->bigInteger('productsId')->unsigned();
            $table->bigInteger('faqId')->unsigned();
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::dropIfExists('products_faq');
    }
}
