<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Aug 31, 2020
*/

class CreateQuestionsTable extends Migration {

    public function up() {
        Schema::create('questions', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('faqId')->nullable()->unsigned();
            $table->string('entryQuestion', 200)->nullable();
            $table->string('exitQuestion', 200)->nullable();
            $table->foreign('faqId')->references('id')->on('faqs');
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::table('faqs', function (Blueprint $table) {
            $table->dropForeign(['faqId']);
        });
        Schema::dropIfExists('questions');
    }
}
