<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Aug 29, 2020
*/

class CreateFaqTable extends Migration {

    public function up() {
        Schema::create('faq', function (Blueprint $table) {
            $table->increments('id');
            $table->string('question', 200)->nullable();
            $table->string('answer', 1000)->nullable();
            $table->string('tags', 100)->nullable();
            $table->integer('verifyScore')->nullable();
            $table->integer('categoryId')->nullable()->unsigned();
            $table->foreign('categoryId')->references('id')->on('categories');
        });
    }

    public function down() {
        Schema::table('categories', function (Blueprint $table) {
            $table->dropForeign(['categoryId']);
        });
        Schema::dropIfExists('faq');
    }
}
