<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Aug 31, 2020
*/

class CreateChangesTable extends Migration {

    public function up() {
        Schema::create('changes', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('faqId')->nullable()->unsigned();
            $table->string('change', 1000)->nullable();
            $table->integer('workerId')->nullable()->unsigned();
            $table->foreign('faqId')->references('id')->on('faqs');
            $table->foreign('workerId')->references('id')->on('workers');
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::table('faqs', function (Blueprint $table) {
            $table->dropForeign(['faqId']);
        });
        Schema::table('workers', function (Blueprint $table) {
            $table->dropForeign(['workerId']);
        });
        Schema::dropIfExists('changes');
    }
}
