<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Aug 31, 2020
*/

class CreateMerchantsTable extends Migration {

    public function up() {
        Schema::create('merchants', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 100)->nullable();
            $table->string('bio', 500)->nullable();
            $table->string('phone', 100)->nullable();
            $table->string('email', 100)->nullable();
            $table->string('address', 200)->nullable();
            $table->string('city', 100)->nullable();
            $table->string('country', 3)->nullable();
            $table->string('rating', 100)->nullable();
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::dropIfExists('merchants');
    }
}
