<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Aug 15, 2020
*/

class CreateVerificationTable extends Migration {

    public function up() {
        Schema::create('verification', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('faqId')->nullable()->unsigned();
            $table->integer('workerId')->nullable()->unsigned();
            $table->foreign('faqId')->references('id')->on('faq');
            $table->foreign('workerId')->references('id')->on('worker');
        });
    }

    public function down() {
        Schema::table('faq', function (Blueprint $table) {
            $table->dropForeign(['faqId']);
        });
        Schema::table('worker', function (Blueprint $table) {
            $table->dropForeign(['workerId']);
        });
        Schema::dropIfExists('verification');
    }
}
