<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Aug 31, 2020
 */

class CreateUsersTable extends Migration
{

	public function up()
	{
		Schema::create('users', function (Blueprint $table) {
			$table->id();
			$table->integer('roleId')->nullable()->unsigned();
			$table->string('name', 100);
			$table->string('phone', 100)->nullable();
			$table->string('email')->unique();
			$table->timestamp('email_verified_at')->nullable();
			$table->string('languages', 100)->nullable();
			$table->string('city', 100)->nullable();
			$table->string('country', 100)->nullable();
			$table->string('password');
			$table->rememberToken();
			$table->timestamps();
			$table->softDeletes();
		});
	}

	public function down()
	{
		Schema::dropIfExists('users');
	}
}
