<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Aug 31, 2020
*/

class CreateProductsTable extends Migration {

    public function up() {
        Schema::create('products', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 100)->nullable();
            $table->string('description', 200)->nullable();
            $table->string('price', 100)->nullable();
            $table->integer('merchantId')->nullable()->unsigned();
            $table->string('photo', 200)->nullable();
            $table->integer('rating')->nullable();
            $table->foreign('merchantId')->references('id')->on('merchants');
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::table('merchants', function (Blueprint $table) {
            $table->dropForeign(['merchantId']);
        });
        Schema::dropIfExists('products');
    }
}
